apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-369015
  artifacts:
    - image: us.gcr.io/ticketing-369015/auth
      # - image: freeflowbc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-369015/client
      # - image: freeflowbc/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/ticketing-369015/tickets
      # - image: freeflowbc/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-369015/orders
      # - image: freeflowbc/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/**/*.ts"
            dest: . skaffold dev
